# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-17 15:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='pup_date',
            new_name='pub_date',
        ),
    ]
